### DISCUSSION TITLE
Parameters used META 3.2 AVISO

### DISCUSSION THREAD

**Discussion by SusanaMSilva** [AntSimi/py-eddy-tracker#264] [General]
Hi!

I have been trying to reproduce the META 3.2 eddy tracking results to make sure that everything is working properly since my objective is to use the py-eddy-tracking on my ROMS model, but I am getting less tracked eddies when compared to the AVISO product. 

I used the parameters below, as they were the ones referred in the manual:
```python
 g = RegularGridDataset(grid_name, lon_name, lat_name)
g.lanczos_high_filter('adt', 700, order=1)
 
a, c = g.eddy_identification('adt','ugos',
    'vgos',  # Variables used for identification
    date,  # Date of identification
    0.002,  # step between two isolines of detection (m)
    pixel_limit=(5, 1000),  # Min and max pixel count for valid contour 
    shape_error=70,  # Error max (%) between ratio of circle fit and contour
)
```
Also, I'm using maps of ADT with a 0.25 resolution, which I think were the same used.
Do I need to add other parameters in the eddy identification? And also, can I change the minimum amplitude?

I then used the eddy traking.yaml:
 ```yaml
PATHS:
  # Files produced with EddyIdentification
  FILES_PATTERN: /py-eddy-tracker/share/Anticyclonic_*.nc
  # Path to save outputs
  SAVE_DIR: 'py-eddy-tracker/share/'

# Number of consecutive timesteps with missing detection allowed
VIRTUAL_LENGTH_MAX: 3
# Minimal number of timesteps to considered as a long trajectory
TRACK_DURATION_MIN: 10

CLASS:
   MODULE: py_eddy_tracker.featured_tracking.area_tracker
   CLASS: AreaTracker
```
Can you help me with this?

Thank you,
Susana Silva
